name: Build & Sign APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Decode Keystore
      run: echo "${{ secrets.RELEASE_KEYSTORE_BASE64 }}" | base64 --decode > my-release-key.jks

    - name: Build APK
      run: ./gradlew assembleRelease

    - name: Sign APK
      run: |
        apksigner sign --ks my-release-key.jks \
          --ks-key-alias "${{ secrets.RELEASE_KEY_ALIAS }}" \
          --ks-pass pass:"${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" \
          --key-pass pass:"${{ secrets.RELEASE_KEY_PASSWORD }}" \
          --out app-release-signed.apk app/build/outputs/apk/release/app-release.apk

    - name: Upload Signed APK
      uses: actions/upload-artifact@v4
      with:
        name: signed-app
        path: app-release-signed.apk
